server.port: 8080
## DataSource
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:postgresql://localhost:5432/companydb
    username: postgres
    password: ton
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true


